routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();


Route::resource('product', ProductController::class);
Route::post('product/add_size', [ProductController::class, 'add_size'])->name('product.add_size');


Route::resource('user', UserController::class);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);


Auth::routes();

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */

    public function __construct()
    {
        //  $this->middleware('abilities:add product', ['only' => 'create','store']);
        //  $this->middleware('abilities:edit product', ['only' => 'edit','update']);
        //  $this->middleware('abilities:delete product', ['only' => 'destroy']);
        //  $this->middleware('abilities:view-product', ['index' => 'show']);

    }
    public function index()
    {
        $products = Product::with('user')->get();
        return $products ;
    }

    public function by_user($id)
    {
        $products = Product::where('user_id', $id)->get();
        return $products;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Size;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\ImageManager;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */

    public function __construct()
    {
        $this->middleware('can:add product', ['only' => 'create','store']);
        $this->middleware('can:edit product', ['only' => 'edit','update']);
        $this->middleware('can:delete product', ['only' => 'destroy']);
        $this->middleware('can:view product', ['index' => 'show']);

    }
    public function index()
    {
        $products = Product::all();
        return view('products.index', compact('products')) ;
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $sizes = Size::all();
        return view('products.create', compact('sizes')) ;
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'image' => 'required|file|mimes:jpeg,jpg,png',
            'name' => 'required',
            'price' => 'required:number',
            'size' => 'required'
        ]);

        $product =  new Product();
        $product->image = $this->save_image($request->file('image'));
        $product->name = $request->name;
        $product->price = $request->price  ;
        $product->size = $request->size ;
        $product->user_id = auth()->user()->id ;
        $product->save() ;

        return redirect()->back()
        ->with('success', 'Product Created Successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(Product $product)
    {
        $sizes = Size::all();
        $product = Product::find($product->id);
        return view('products.show', compact('product','sizes')) ;

    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $product)
    {
        $sizes = Size::all();
        $product = Product::find($product->id);
        return view('products.edit', compact('product', 'sizes')) ;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'image' => 'required|file|mimes:jpeg,jpg,png',
            'name' => 'required',
            'price' => 'required:number',
            'size' => 'required'
        ]);

        $product =  Product::find($product->id);
        $product->image = $this->save_image($request->file('image'));
        $product->name = $request->name;
        $product->price = $request->price  ;
        $product->size = $request->size ;
        $product->user_id = auth()->user()->id ;
        $product->save() ;

        return redirect()->back()
        ->with('success', 'Product Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        Product::find($product->id)->delete();
        return redirect()-back()
            ->with('success', "Deleted Successfully");
    }

    public function add_size(Request $request)
    {
        $size = new Size();
        $size->name = $request->name;
        $size->save();
        return redirect()->back()
        ->with('success', 'Added Successfully');
    }

    protected function save_image($image)
    {
        $fileName   = time() . '.' . $image->getClientOriginalExtension();

        // create an image manager instance with favored driver
        $manager = new ImageManager(['driver' => 'imagick']);
        $img = $manager->make($image->getRealPath());
        // $img->resize(120, 120, function ($constraint) {
        //     $constraint->aspectRatio();
        // });
        $img->stream(); // <-- Key point
        //dd();
        Storage::disk('public')->put('images/products' . '/' . $fileName, $img, 'public');
        return $fileName;
    }

}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Create Product</h2>
                </div>
            </div>
        </div>
        <form action="{{ route('product.store') }}" id="create-product-form" method="post" enctype="multipart/form-data">
            @csrf
            @method('POST')
            <div class="mb-3">
                <label for="name">Prodcut Name</label>
                <input type="text" name="name" class="form-control" id="name">
            </div>
            <div class="mb-3">
                <label for="image" class="form-label">Product Image</label>
                <input class="form-control" type="file" id="image" name="image" accept="image/*">
            </div>
            <div class="mb-3 row align-items-end">

                <div class="col">
                    <label for="size" class="form-label">Size</label>
                    <select class="form-select" name="size" id="size">
                        @foreach ($sizes as $size)
                            <option value="{{ $size->name }}">{{ $size->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Add Size
                    </button>
                </div>
            </div>
            <div class="mb-3">
                <label for="price">Price</label>
                <input type="number" name="price" class="form-control" id="price">
            </div>
            <button type="submit" class="btn btn-primary">Save </button>
        </form>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Size</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('product.add_size') }}" id="add-size-form" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="name">Size</label>
                            <input type="text" name="name" class="form-control" id="name">
                        </div>
                        <button type="submit" class="btn btn-primary">Add</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
@endpush

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Edit Product</h2>
                </div>
            </div>
        </div>
        <form action="{{ route('product.update', $product->id) }}" id="edit-product-form" method="post"
            enctype="multipart/form-data">
            @csrf
            @method('PATCH')
            <input type="hidden" name="id" value="{{ $product->id }}">
            <div class="mb-3">
                <label for="name">Prodcut Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{ $product->name }}">
            </div>

            <div class="mb-3 row">
                <div class="col">
                    <label for="image" class="form-label">Product Image</label>
                    <input class="form-control" type="file" id="image" name="image" accept="image/*">
                </div>
                <div class="col">
                    <img src="{{ Storage::disk('public')->url('images/products/' . $product->image) }}" alt=""
                        class="img-fluid">
                </div>

            </div>
            <div class="mb-3 row align-items-end">

                <div class="col">
                    <label for="size" class="form-label">Size</label>
                    <select class="form-select" name="size" id="size">
                        @foreach ($sizes as $size)
                            <option value="{{ $size->name }}" {{ $product->size == $size->name ? 'selected' : '' }}>
                                {{ $size->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Add Size
                    </button>
                </div>
            </div>
            <div class="mb-3">
                <label for="price">Price</label>
                <input type="number" name="price" class="form-control" id="price" value="{{ $product->price }}">
            </div>
            <button type="submit" class="btn btn-success">Edit </button>
        </form>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Size</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('product.add_size') }}" id="add-size-form" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="name">Size</label>
                            <input type="text" name="name" class="form-control" id="name">
                        </div>
                        <button type="submit" class="btn btn-primary">Add</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
@endpush

resources/views/products/index.blade.php
@extends('layouts.app')

@push('styles')
    <style>
        th,
        td {
            text-align: center !important;
        }
    </style>
@endpush

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="pull-left">
                    <h2>Products</h2>
                </div>
                @can('add product')
                    <div class="pull-right">
                        <a class="btn btn-success" href="{{ route('product.create') }}">Create Product</a>
                    </div>
                @endcan
            </div>
        </div>
        <hr>
        <table class="table table-striped default-datatable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Image</th>
                    <th>Size</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $key => $product)
                    <tr>
                        <td>{{ $product->id }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->image }}</td>
                        <td>{{ $product->size }}</td>
                        <td>{{ $product->price }}</td>
                        <td class="d-flex justify-content-center align-items-center">
                            @can('view product')
                                <a class="btn btn-transparent" href="{{ route('product.show', $product->id) }}"><i
                                        class="fa fa-eye text-warning"></i></a>
                            @endcan
                            @can('edit product')
                                <a class="btn btn-transparent" href="{{ route('product.edit', $product->id) }}"><i
                                        class="fa fa-edit text-success"></i></a>
                            @endcan
                            @can('delete product')
                                <form action="{{ route('product.destroy', $product->id) }}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-transparent btn-prompt"><i
                                            class="fa fa-trash text-danger"></i></button>
                                </form>
                            @endcan
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Product Details</h2>
                </div>
            </div>
        </div>
        <form action="{{ route('product.update', $product->id) }}" id="edit-product-form" method="post"
            enctype="multipart/form-data" disabled>
            @csrf
            @method('PATCH')
            <input type="hidden" name="id" value="{{ $product->id }}">
            <div class="mb-3">
                <label for="name">Prodcut Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{ $product->name }}" disabled readonly>
            </div>

            <div class="mb-3 row">
                <div class="col">
                    <img src="{{ Storage::disk('public')->url('images/products/' . $product->image) }}" alt=""
                        class="img-fluid">
                </div>

            </div>
            <div class="mb-3">
                <label for="size" class="form-label">Size</label>
                <select class="form-select" name="size" id="size" readonly disabled>
                    @foreach ($sizes as $size)
                        <option value="{{ $size->name }}" {{ $product->size == $size->name ? 'selected' : '' }}>
                            {{ $size->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-3">
                <label for="price">Price</label>
                <input type="number" name="price" class="form-control" id="price" value="{{ $product->price }}" disabled readonly>
            </div>
        </form>
    </div>
@endsection


@push('scripts')
@endpush